FROM php:8-fpm-alpine

ARG UID
ARG GID

ENV UID=${UID}
ENV GID=${GID}

RUN apk update && apk upgrade

RUN apk add \
    curl \
    oniguruma-dev \
    libpq-dev \
    zlib-dev \
    libpng-dev \
    zip \
    unzip \
    shadow \
    sudo

RUN rm -f /var/cache/apk/*

RUN docker-php-ext-install pdo pdo_pgsql mbstring exif pcntl bcmath gd

WORKDIR /var/www/html

COPY --from=composer:2.3.7 /usr/bin/composer /usr/bin/composer

RUN addgroup -g ${GID} --system laravel
RUN adduser -G laravel --system -D -s /bin/sh -u ${UID} laravel

RUN sed -i "s/user = www-data/user = laravel/g" /usr/local/etc/php-fpm.d/www.conf
RUN sed -i "s/group = www-data/group = laravel/g" /usr/local/etc/php-fpm.d/www.conf

USER laravel

COPY --chown=laravel:laravel . .

RUN composer install --prefer-dist

CMD ["php-fpm", "-y", "/usr/local/etc/php-fpm.conf", "-R"]
